services:
  service:
    image: ${DESKTOP_PLUGIN_IMAGE}
    volumes:
      - type: bind
        source: /var/run/docker.sock.raw
        target: /var/run/docker.sock
    # No external port mapping - extension runs inside Docker Desktop VM
    expose:
      - "8080"
    command: /backend/ddalab-manager
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s