FROM alpine:latest

COPY ui /ui
COPY metadata-simple.json /metadata.json
COPY icon.svg /icon.svg

LABEL org.opencontainers.image.title="DDALAB Manager" \
      org.opencontainers.image.description="Manage DDALAB installations" \
      org.opencontainers.image.vendor="DDALAB Team" \
      com.docker.desktop.extension.api.version="0.3.4"